#!/bin/bash
export VOLUME=${1:-/tmp/volume1/}
export TYPE=volume
#cargo run
target/release/blobstorage
#uwsgi --disable-logging --http :${PORT:-3001} --wsgi-file server.py --callable volume --master --processes 4
